name: Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    name: Test on Node.js ${{ matrix.node-version }}
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        node-version: [14, 16, 18, 20]
        os: [ubuntu-latest, windows-latest, macos-latest]
        
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Test CLI help
        run: node index.js --help
        
      - name: Test version command
        run: node index.js --version
        
      - name: Test release help
        run: node index.js release --help
        
      - name: Test version help  
        run: node index.js up version --help
        
      - name: Create test project
        run: |
          mkdir test-project
          cd test-project
          echo '{"name": "test", "version": "1.0.0"}' > package.json
          echo '# Test Changelog' > CHANGELOG.md
          echo '## [Unreleased]' >> CHANGELOG.md
          git init
          git config user.name "Test"
          git config user.email "test@example.com"
          git add .
          git commit -m "Initial commit"
          git branch -M main
          
      - name: Test version bump in test project
        working-directory: test-project
        run: |
          node ../index.js up version patch
          grep -q "1.0.1" package.json || (echo "Version not updated" && exit 1)
          
  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Check for syntax errors
        run: |
          node -c index.js
          node -c src/utils.js
          node -c src/git.js
          node -c src/version.js
          node -c src/changelog.js
          node -c src/development.js
          node -c src/release.js
